# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  init:
    desc: Install npm dependencies
    cmds:
      - npm install

  typecheck:
    desc: TypeScript type checking
    cmds:
      - npx tsc --noEmit
