# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  frontend:
    taskfile: ./frontend/Taskfile.yml
    dir: ./frontend
  core:
    taskfile: ./services/core/Taskfile.yml
    dir: ./services/core
  odds:
    taskfile: ./services/odds/Taskfile.yml
    dir: ./services/odds
  wallet:
    taskfile: ./services/wallet/Taskfile.yml
    dir: ./services/wallet

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "Hello, world!"
    silent: true

  init:
    desc: Install dependencies for all services in parallel
    deps:
      - frontend:init
      - core:init
      - odds:init
      - wallet:init

  typecheck:
    desc: Run type checking for all services in parallel
    deps:
      - frontend:typecheck
      - core:typecheck
      - odds:typecheck
      - wallet:typecheck
