#!/usr/bin/env node
// gen-zod.mjs — generates a single Zod module from every JSON Schema document
// in a directory.
//
// Reads each `*.json` in <schema-dir> and emits one output module
// exporting, for every `$def` across all of them:
//   export const <Name>Schema = z.<...>;
//   export type <Name> = z.infer<typeof <Name>Schema>;
//
// The schemas are denormalised (no intra-document `$ref`s), so each `$def` is
// fed straight to json-schema-to-zod.
//
// Usage: node tools/gen-zod.mjs <schema-dir> <output-file>
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { jsonSchemaToZod } from "json-schema-to-zod";

const [schemaDir, out] = process.argv.slice(2);
if (!schemaDir || !out) {
  console.error("usage: node gen-zod.mjs <schema-dir> <output-file>");
  process.exit(1);
}

const files = readdirSync(schemaDir)
  .filter((f) => f.endsWith(".json"))
  .sort();

const blocks = [];
for (const file of files) {
  const defs = JSON.parse(readFileSync(join(schemaDir, file), "utf8")).$defs ?? {};
  for (const name of Object.keys(defs)) {
    const body = jsonSchemaToZod(defs[name], { module: "none", type: false });
    blocks.push(
      `export const ${name}Schema = ${body};\nexport type ${name} = z.infer<typeof ${name}Schema>;`,
    );
  }
}

const header =
  "// GENERATED by tools/gen-zod.mjs from schemas/json/*.json — DO NOT EDIT.\n" +
  'import { z } from "zod";\n';
writeFileSync(out, `${header}\n${blocks.join("\n\n")}\n`);
console.log(`wrote ${blocks.length} schemas -> ${out}`);
