#!/usr/bin/env node
// gen-zod.mjs — generates a Zod module from schemas/events.schema.json.
//
// Emits one `src/generated/events.ts` exporting, for every `$def`:
//   export const <Name>Schema = z.<...>;
//   export type <Name> = z.infer<typeof <Name>Schema>;
//
// The schema is denormalised (no intra-document `$ref`s), so each `$def` is
// fed straight to json-schema-to-zod.
//
// Usage: node tools/gen-zod.mjs <output-file>
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { jsonSchemaToZod } from "json-schema-to-zod";

const here = dirname(fileURLToPath(import.meta.url));
const schemaPath = resolve(here, "../schemas/events.schema.json");
const out = process.argv[2];
if (!out) {
  console.error("usage: node gen-zod.mjs <output-file>");
  process.exit(1);
}

const schema = JSON.parse(readFileSync(schemaPath, "utf8"));
const defs = schema.$defs ?? {};

const blocks = Object.keys(defs).map((name) => {
  const body = jsonSchemaToZod(defs[name], { module: "none", type: false });
  return `export const ${name}Schema = ${body};\nexport type ${name} = z.infer<typeof ${name}Schema>;`;
});

const header =
  "// GENERATED by tools/gen-zod.mjs from schemas/events.schema.json — DO NOT EDIT.\n" +
  'import { z } from "zod";\n';
writeFileSync(out, `${header}\n${blocks.join("\n\n")}\n`);
console.log(`wrote ${blocks.length} schemas -> ${out}`);
