# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  init:
    desc: Create virtualenv and install dependencies
    cmds:
      - python -m venv .venv
      - .venv/bin/pip install -e ".[dev]"

  # TODO use one virtualenv for python projects to use less resources
  typecheck:
    desc: mypy type checking
    cmds:
      - python -m mypy src/
